package com.myspace.proyectogestioncredito.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Primer Nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label(value = "Segundo Nombre")
	private java.lang.String segundoNombre;
	@org.kie.api.definition.type.Label(value = "SegundoApellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label(value = "Segundo Apellido")
	private java.lang.String segundoApellido;
	@org.kie.api.definition.type.Label(value = "Tipo Identificacion")
	private java.lang.String tipoId;
	@org.kie.api.definition.type.Label(value = "Numero Identificacion")
	private java.lang.Integer identificacion;
	@org.kie.api.definition.type.Label(value = "Fecha de Nacimiento")
	private java.util.Date fechaNacimiento;

	public Cliente() {
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(java.lang.String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public java.lang.String getTipoId() {
		return this.tipoId;
	}

	public void setTipoId(java.lang.String tipoId) {
		this.tipoId = tipoId;
	}

	public java.lang.Integer getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(java.lang.Integer identificacion) {
		this.identificacion = identificacion;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Cliente(java.lang.String primerNombre,
			java.lang.String segundoNombre, java.lang.String primerApellido,
			java.lang.String segundoApellido, java.lang.String tipoId,
			java.lang.Integer identificacion, java.util.Date fechaNacimiento) {
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoId = tipoId;
		this.identificacion = identificacion;
		this.fechaNacimiento = fechaNacimiento;
	}

}