package com.myspace.proyectogestioncredito.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DescripcionAprobacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "aprobacion")
	private java.lang.String aprobacion;
	@org.kie.api.definition.type.Label(value = "Motivo")
	private java.lang.String motivo;

	public DescripcionAprobacion() {
	}

	public java.lang.String getAprobacion() {
		return this.aprobacion;
	}

	public void setAprobacion(java.lang.String aprobacion) {
		this.aprobacion = aprobacion;
	}

	public java.lang.String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(java.lang.String motivo) {
		this.motivo = motivo;
	}

	public DescripcionAprobacion(java.lang.String aprobacion,
			java.lang.String motivo) {
		this.aprobacion = aprobacion;
		this.motivo = motivo;
	}

}