package com.myspace.proyectogestioncredito.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DescripcionSoliCred implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fecha Solicitud")
	private java.util.Date fechaSolicitud;
	@org.kie.api.definition.type.Label("Id Solicitud")
	private java.lang.Integer idSoli;
	@org.kie.api.definition.type.Label("Valor Credito")
	private Integer valorCredito;
	@org.kie.api.definition.type.Label("Tiempo Total Amortizacion(Meses)")
	private Integer tiempoTotalAmort;
	@org.kie.api.definition.type.Label("Salario")
	private Integer salario;
	@org.kie.api.definition.type.Label("Gastos/Mes")
	private Integer gastos;

	public DescripcionSoliCred() {
	}

	public java.util.Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(java.util.Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public java.lang.Integer getIdSoli() {
		return this.idSoli;
	}

	public void setIdSoli(java.lang.Integer idSoli) {
		this.idSoli = idSoli;
	}

	public java.lang.Integer getValorCredito() {
		return this.valorCredito;
	}

	public void setValorCredito(java.lang.Integer valorCredito) {
		this.valorCredito = valorCredito;
	}

	public java.lang.Integer getTiempoTotalAmort() {
		return this.tiempoTotalAmort;
	}

	public void setTiempoTotalAmort(java.lang.Integer tiempoTotalAmort) {
		this.tiempoTotalAmort = tiempoTotalAmort;
	}

	public java.lang.Integer getSalario() {
		return this.salario;
	}

	public void setSalario(java.lang.Integer salario) {
		this.salario = salario;
	}

	public java.lang.Integer getGastos() {
		return this.gastos;
	}

	public void setGastos(java.lang.Integer gastos) {
		this.gastos = gastos;
	}

	public DescripcionSoliCred(java.util.Date fechaSolicitud,
			java.lang.Integer idSoli, java.lang.Integer valorCredito,
			java.lang.Integer tiempoTotalAmort, java.lang.Integer salario,
			java.lang.Integer gastos) {
		this.fechaSolicitud = fechaSolicitud;
		this.idSoli = idSoli;
		this.valorCredito = valorCredito;
		this.tiempoTotalAmort = tiempoTotalAmort;
		this.salario = salario;
		this.gastos = gastos;
	}

}